from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial=True
    dependencies=[migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
        migrations.CreateModel(name='Destination',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=120)),('state',models.CharField(blank=True,max_length=120)),('tag',models.CharField(blank=True,max_length=60)),('emoji',models.CharField(default='📍',max_length=8)),('color',models.CharField(default='#9FE1CB',max_length=20)),('duration',models.CharField(blank=True,max_length=40)),('budget',models.CharField(blank=True,max_length=40)),('description',models.TextField(blank=True)),('created_at',models.DateTimeField(auto_now_add=True))],options={'ordering':['name']}),
        migrations.CreateModel(name='Profile',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('location',models.CharField(blank=True,max_length=120)),('bio',models.TextField(blank=True)),('avatar_initials',models.CharField(blank=True,max_length=8)),('states_explored',models.PositiveIntegerField(default=0)),('countries_explored',models.PositiveIntegerField(default=0)),('user',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='profile',to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='Story',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('location',models.CharField(blank=True,max_length=150)),('title',models.CharField(max_length=220)),('excerpt',models.TextField(blank=True)),('body',models.TextField(blank=True)),('category',models.CharField(default='Story',max_length=60)),('story_type',models.CharField(choices=[('Story','Story'),('Photos','Photos'),('Video','Video'),('Tip','Tip')],default='Story',max_length=20)),('tags',models.JSONField(blank=True,default=list)),('read_time',models.CharField(default='5 min',max_length=30)),('thumbnail',models.CharField(default='#B5D4F4',max_length=20)),('created_at',models.DateTimeField(auto_now_add=True)),('author',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='stories',to=settings.AUTH_USER_MODEL))],options={'ordering':['-created_at']}),
        migrations.CreateModel(name='Question',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('title',models.CharField(max_length=240)),('body',models.TextField(blank=True)),('category',models.CharField(choices=[('Visa & Docs','Visa & Docs'),('Budget & Costs','Budget & Costs'),('Safety','Safety'),('Packing','Packing'),('Accommodation','Accommodation'),('Transport','Transport')],default='Budget & Costs',max_length=60)),('solved',models.BooleanField(default=False)),('views',models.PositiveIntegerField(default=0)),('created_at',models.DateTimeField(auto_now_add=True)),('author',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='questions',to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='Trip',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=150)),('location',models.CharField(blank=True,max_length=150)),('start_date',models.DateField(blank=True,null=True)),('duration',models.CharField(blank=True,max_length=40)),('emoji',models.CharField(default='🗺️',max_length=8)),('color',models.CharField(default='#B5D4F4',max_length=20)),('status',models.CharField(choices=[('Upcoming','Upcoming'),('Completed','Completed'),('Planning','Planning')],default='Planning',max_length=20)),('notes',models.TextField(blank=True)),('owner',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='trips',to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='Answer',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('text',models.TextField()),('is_top',models.BooleanField(default=False)),('created_at',models.DateTimeField(auto_now_add=True)),('author',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to=settings.AUTH_USER_MODEL)),('question',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='answers',to='api.question'))]),
        migrations.CreateModel(name='Comment',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('text',models.TextField()),('created_at',models.DateTimeField(auto_now_add=True)),('author',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to=settings.AUTH_USER_MODEL)),('story',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='comments',to='api.story'))]),
        migrations.CreateModel(name='Follow',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('follower',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='following',to=settings.AUTH_USER_MODEL)),('following',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='followers',to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='StoryLike',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('story',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='likes',to='api.story')),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='StorySave',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('created_at',models.DateTimeField(auto_now_add=True)),('story',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='saves',to='api.story')),('user',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to=settings.AUTH_USER_MODEL))]),
        migrations.AddConstraint(model_name='follow',constraint=models.UniqueConstraint(fields=('follower','following'),name='unique_follow')),
        migrations.AddConstraint(model_name='storylike',constraint=models.UniqueConstraint(fields=('story','user'),name='unique_story_like')),
        migrations.AddConstraint(model_name='storysave',constraint=models.UniqueConstraint(fields=('story','user'),name='unique_story_save')),
    ]
