# Generated by Django 5.2.17 on 2026-09-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_story_category_storymedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='category',
            field=models.CharField(default='Story', max_length=30),
        ),
    ]
